# Database connection issues without gssencmode: disable
# https://stackoverflow.com/questions/59089991/ruby-2-6-5-and-postgresql-pg-gem-segmentation-fault

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  checkout_timeout: <%= ENV['DB_TIMEOUT'] || 5 %>
  host: localhost
  username: postgres

development:
  <<: *default
  database: hometime_cc_development
  gssencmode: disable
test:
  <<: *default
  database: hometime_cc_test
  gssencmode: disable
production:
  <<: *default
  database: hometime_cc_production
  username: hometime_cc
  password: <%= ENV['HOMETIME_CC_DATABASE_PASSWORD'] %>
